'use strict';var XF={TAB:0,cg:1,Zi:2},YF=function(a){ai("MediaRouter.CastStreaming.Start.Success",a,XF)};var ZF=v("mr.mirror.cast.LogUploader"),aG=function(a,b,c){$F("raw_events.log.gz",a,b,c);return b?"https://crash.corp.google.com/samples?stbtiq="+b:""},$F=function(a,b,c,d){if(0==b.size)x(ZF,"Trying to upload an empty file to Crash"),d&&d(null);else{var e=new FormData;e.append("prod","Cast");e.append("ver",chrome.runtime.getManifest().version);e.append(a,b);c&&e.append("comments",c);Qf("https://clients2.google.com/cr/report",function(a){a=a.target;var b=null;We(a)?(b=Xe(a),x(ZF,"Upload to Crash succeeded: "+
b)):x(ZF,"Upload to Crash failed. HTTP status: "+a.xa());d&&d(b)},"POST",e,void 0,3E4)}};var bG=function(){this.a=0;rj(this)},dG=function(){cG||(cG=new bG);return cG},eG=function(){var a=dG(),b={fraction:.01,autoSubmitTimeLimitMillis:6048E5},c=b.autoSubmitTimeLimitMillis,d=Date.now();return a.a&&c&&d-a.a<c?!1:Math.random()<b.fraction},gG=function(a,b,c,d){var e=new fG;e.extVersion=chrome.runtime.getManifest().version;e.extChannel="public";e.minBitrate=c.minVideoBitrate;e.maxBitrate=c.maxVideoBitrate;e.resolution=c.maxWidth+"x"+c.maxHeight;e.minResolution=c.minWidth+"x"+c.minHeight;if(e.minResolution==
e.resolution)e.resolutionChangePolicy="fixed";else if(c.senderSideLetterboxing){var f=Qh(c);e.minResolution+=" (altered to: "+f.width+"x"+f.height+")";e.resolutionChangePolicy="fixed-aspect-ratio"}else e.resolutionChangePolicy="variable";e.maxFrameRate=c.maxFrameRate;e.minLatency=c.minLatencyMillis;e.maxLatency=c.maxLatencyMillis;e.animatedLatency=c.animatedLatencyMillis;e.useDscp=c.dscpEnabled;e.useTdls=c.useTdls;null!=b&&(e.receiverVersion=b);null!=a&&(e.receiverProductName=a);d.length&&(e.receiverStatusData=
d);return e},iG=function(a,b,c,d,e){x(hG,"getRawEvents");return new Promise(function(f,g){var m=function(b){x(hG,"Got receiver version: "+b);b=JSON.stringify(gG(c,b,d,e));chrome.cast.streaming.rtpStream.getRawEvents(a,b,f)};"Chromecast"==c?lg(b).then(m,g):m(null)})},jG=function(a,b,c,d){x(hG,"getStats");return new Promise(function(e,f){var g=function(b){x(hG,"Got receiver version: "+b);var f=gG(c,b,d,[]);chrome.cast.streaming.rtpStream.getStats(a,function(a){var b={tags:f};Wa(b,a);e(b)})};"Chromecast"==
c?lg(b).then(g,f):g(null)})};bG.prototype.fa=function(){return"mirror.cast.LogUtils"};bG.prototype.qa=function(){return[void 0,{lastAutoSubmitMillis:this.a}]};bG.prototype.va=function(){var a=pj(this);this.a=a&&a.lastAutoSubmitMillis||0};var cG=null,hG=v("mr.mirror.cast.LogUtils"),fG=function(){this.ext="MR";this.senderProductName="Google Chrome";this.senderVersion=Kn;this.senderPlatform=oc;this.senderUserAgent=ub||""};var kG=v("mr.NetworkUtils"),lG=function(a,b){return Kh?new Promise(function(c,d){chrome.networkingPrivate.setWifiTDLSEnabledState(a,b,function(a){chrome.runtime.lastError?(w(kG,"Unable to set TDLS state: state = "+b+", error = "+chrome.runtime.lastError.message),d("Unable to set TDLS state to "+b+".")):(x(kG,"TDLS state changed: state = "+b+", status = "+a),c(a))})}):Promise.reject("TDLS feature not enabled.")};var mG=function(){this.a=Promise.resolve(1)},oG=function(a,b,c){return nG(a,function(a){return a==b},c)},pG=function(a,b){var c=[3,4];return nG(a,function(a){return-1!=c.indexOf(a)},b)},qG=function(a,b){a.a=a.a.catch(function(){return 1});return nG(a,function(){return!0},b)},nG=function(a,b,c){var d,e,f=new Promise(function(a,b){d=a;e=b});a.a=a.a.then(function(a){if(!b(a))return e(Error("Operation requires a different starting checkpoint than "+a)),Promise.resolve(a);var f=new rG(a),g;try{g=c(f)}catch(y){g=
Promise.reject(y)}return g.then(function(a){return d(a)},function(a){return e(a)}).then(function(){if(null===f.a)throw Error("A prior operation that started at "+(a+" did not complete."));return f.a})},function(a){e(a);throw a;});return f},rG=function(a){this.b=a;this.a=null},sG=function(a,b){a.a="number"===typeof b?b:a.b};var tG={up:"OFFER",wm:"ANSWER",Np:"PRESENTATION",Nn:"GET_STATUS",yq:"STATUS_RESPONSE",Mn:"GET_CAPABILITIES",Pm:"CAPABILITIES_RESPONSE",lq:"RPC"};var uG=function(){this.capabilities=this.status=this.a=this.error=this.rpc=this.result=this.type=this.b=this.sessionId=null},xG=function(a){var b;try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var c;vG(JSON.parse(a),function(a){c=wG(a)},function(){throw Error("non-Object result from JSON parse");});return c}catch(d){b=d instanceof SyntaxError?"JSON parse error: "+d.message:"Type coercion error: "+d.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(b+". Input was "+a);},wG=function(a){var b=new uG;null!=a.sessionId&&(b.sessionId=String(a.sessionId));yG(a.seqNum,function(a){b.b=a},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var c=String(a.type).toUpperCase(),d=ja(Object.keys(tG)),e=d.next();!e.done;e=d.next())if(tG[e.value]==c){b.type=c;break}if(!b.type)throw Error('not a known message "type"');
}"result"in a&&(b.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');b.rpc=new Uint8Array([].concat(la(atob(a.rpc))).map(function(a){return a.charCodeAt(0)}))}vG(a.error,function(a){b.error=zG(a)},function(){throw Error('"error" must be an Object');});vG(a.answer,function(a){b.a=AG(a)},function(){throw Error('"answer" must be an Object');});vG(a.status,function(a){b.status=BG(a)},function(){throw Error('"status" must be an Object');
});vG(a.capabilities,function(a){b.capabilities=CG(a)},function(){throw Error('"capabilities" must be an Object');});return b},vG=function(a,b,c){void 0!==a&&(a instanceof Object?b(a):c())},yG=function(a,b,c){void 0!==a&&("number"!==typeof a?c():b(a))},DG=function(a,b,c){void 0!==a&&(a instanceof Array&&a.every(function(a){return"number"===typeof a})?b(a):c())},EG=function(a,b,c){void 0!==a&&(a instanceof Array?b(a.map(function(a){return String(a)})):c())},FG=function(){this.g=null;this.a=[];this.b=
[];this.f=this.h=this.j=null},AG=function(a){var b=new FG;yG(a.udpPort,function(a){b.g=a},function(){throw Error('"answer.udpPort" must be a number');});DG(a.sendIndexes,function(a){b.a=a},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});DG(a.ssrcs,function(a){b.b=a},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(b.j=String(a.IV));"receiverGetStatus"in a&&(b.h="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&(b.f=String(a.castMode));
return b},GG=function(){this.details=this.description=this.code=null},zG=function(a){var b=new GG;yG(a.code,function(a){b.code=a},function(){throw Error('"error.code" must be a number');});"description"in a&&(b.description=String(a.description));vG(a.details,function(a){b.details=a},function(){throw Error('"error.details" must be an Object');});return b},HG=function(){this.b=this.a=null},BG=function(a){var b=new HG;yG(a.wifiSnr,function(a){b.a=a},function(){throw Error('"status.wifiSnr" must be a number');
});DG(a.wifiSpeed,function(a){b.b=a},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return b},IG=function(){this.b=this.a=null},CG=function(a){var b=new IG;EG(a.mediaCaps,function(a){b.a=a},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');b.b=a.map(function(a){var b;vG(a,function(a){b=JG(a)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return b})}return b},KG=function(){this.f=this.m=this.j=this.g=this.v=this.a=this.w=this.b=this.initDataTypes=this.h=null},JG=function(a){var b=new KG;"keySystemName"in a&&(b.h=String(a.keySystemName));EG(a.initDataTypes,function(a){b.initDataTypes=a},function(){throw Error('"capabilities.initDataTypes" must be an array');});EG(a.codecs,function(a){b.b=a},function(){throw Error('"capabilities.codecs" must be an array');});EG(a.secureCodecs,function(a){b.w=a},function(){throw Error('"capabilities.secureCodecs" must be an array');
});EG(a.audioRobustness,function(a){b.a=a},function(){throw Error('"capabilities.audioRobustness" must be an array');});EG(a.videoRobustness,function(a){b.v=a},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(b.g=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(b.j=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(b.m=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(b.f=String(a.distinctiveIdentifierSupport));return b};var LG=function(a){this.l=v("mr.mirror.cast.MessageDispatcher");this.h=a;this.a=null;this.b=new Map;this.f=0},MG=function(a,b,c){if(a.b.has(b))throw Error("Attempt to multiple-subscribe to the same response type: "+b);a.b.set(b,c);a.f=0;z(a.l,"Added subscriber for "+b+"-type messages.");a.a||(a.a=sp(a.h),a.a.onMessage=a.g.bind(a))},NG=function(a,b){a.b.delete(b)&&z(a.l,function(){return"Removed subscriber of "+b+"-type messages."});0==a.b.size&&a.a&&(a.a.pa(),a.a=null)};
LG.prototype.sendMessage=function(a){return this.a?"RPC"==a.type?this.a.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.a.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
var OG=function(a,b,c,d,e){var f=null,g=function(){NG(a,c);null!=f&&(clearTimeout(f),f=null)};try{MG(a,c,function(a){e(a)&&g()})}catch(m){e(null,m);return}f=setTimeout(function(){g();e(null,Error("timeout"))},d);a.sendMessage(b).catch(function(a){g();e(null,a)})};
LG.prototype.g=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){var b;do{b=void 0;try{b=xG(a.data)}catch(d){b=d.message;break}if(b.type){var c=this.b.get(b.type);if(c)try{c(b);return}catch(d){b="Error thrown during delivery. Response was: "+(JSON.stringify(b)+". Error from subscriber callback ")+("was: "+d.message+".")}else b="Message was ignored: "+JSON.stringify(b)}else b="Message did not include response type: "+JSON.stringify(b)}while(0);
10>this.f?w(this.l,b):z(this.l,b);++this.f}};var PG=chrome.cast.streaming,RG=function(a,b,c,d,e){this.F=a.sessionId;this.j=a.Pf;this.m=a.ji;this.b=b;this.J=c;this.B=d;this.H=QG(e,"onAnswer",this.j);this.ia=QG(e,"onSessionStop",this.j);this.l=v("mr.mirror.cast.StreamingLaunchWorkflow");this.o=new mG;this.w=this.u=this.v=this.f=this.a=this.g=this.h=null};
RG.prototype.start=function(a,b,c){var d=this;if(!a&&!b)return Promise.reject(Error("No tracks to stream"));var e=a instanceof SG,f=b instanceof SG;(e&&b&&!f||f&&a&&!e)&&tb("Mixing remoting and non-remoting tracks");return oG(this.o,1,function(e){d.h=a;d.g=b;x(d.l,function(){return"Launching streaming for "+TG(d)+" "+("to a "+d.m+".")});return UG(d).then(d.A.bind(d)).then(function(a){return VG(d,a).then(function(b){d.H();var e=WG(d,b,a);d.a=XG(d,d.a,e);d.f=XG(d,d.f,e);if(!d.a&&!d.f)throw Error("Receiver did not select any offers from: "+
JSON.stringify(a));d.u=!!b.h;d.w=function(a,b){a==d.a?c("Audio stream (id="+a+") error: "+b):a==d.f&&c("Video stream (id="+a+") error: "+b)};PG.rtpStream.onError.addListener(d.w);return YG(d,b,e)})}).then(function(){x(d.l,function(){return"Launched streaming for "+TG(d)});sG(e,2);return{Bg:null!=d.a?d.a.toString(16):null,ti:null!=d.f?d.f.toString(16):null}})})};
RG.prototype.stop=function(){var a=this;return qG(this.o,function(b){if(a.h||a.g)x(a.l,function(){return"Stopping streaming for "+TG(a)+"."}),a.w&&(PG.rtpStream.onError.removeListener(a.w),a.w=null),a.a&&(PG.rtpStream.stop(a.a),PG.rtpStream.destroy(a.a),a.a=null),a.f&&(PG.rtpStream.stop(a.f),PG.rtpStream.destroy(a.f),a.f=null),a.v&&(PG.udpTransport.destroy(a.v),a.v=null),a.ia(),x(a.l,function(){return"Stopped streaming for "+TG(a)+"."}),a.h=null,a.g=null;sG(b,1);return Promise.resolve()})};
var ZG=function(a,b){return Promise.all([a.a&&iG(a.a,a.j,a.m,a.b,b),a.f&&iG(a.f,a.j,a.m,a.b,b)]).then(function(b){b=new Blob(b.filter(function(a){return!!a}),{type:"application/gzip"});if(0==b.size)throw Error("No logs available to retrieve.");x(a.l,"Events blob size: "+b.size);return b})};
RG.prototype.getStats=function(a){return Promise.all([this.a&&jG(this.a,this.j,this.m,this.b),this.f&&jG(this.f,this.j,this.m,this.b),0<a.length?{receiverStatusData:a}:void 0]).then(function(a){a=Object.assign.apply(Object,[].concat([{}],la(a.filter(function(a){return!!a}))));if(0==Object.getOwnPropertyNames(a).length)throw Error("No stats available to retrieve.");return a})};
var TG=function(a){var b;b=a.h&&a.g?"audio+video ":a.h?"audio-only ":a.g?"video-only ":"";return a.h instanceof SG||a.g instanceof SG?b+"remoting":b+"streaming"},UG=function(a){return new Promise(function(b){var c=function(c,e,f){c&&!a.h&&(PG.rtpStream.destroy(c),c=null);e&&!a.g&&(PG.rtpStream.destroy(e),e=null);x(a.l,function(){return"Created Cast Streaming session: audioStreamId="+c+", videoStreamId="+e+"."});a.a=c;a.f=e;a.v=f;b()};a.h instanceof SG||a.g instanceof SG?PG.session.create(null,null,
c):PG.session.create(a.h,a.g,c)})};
RG.prototype.A=function(){for(var a=Xj(),b=Xj(),c=[],d=ja([this.a,this.f]),e=d.next();!e.done;e=d.next())if(e=e.value)for(var f=e==this.a,g=f?127:96,m=f?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,q=f?48E3:9E4,y=ja(PG.rtpStream.getSupportedParams(e)),D=y.next();!D.done;D=y.next())D=D.value,D.payload.payloadType=g,D.payload.maxLatency=this.b.maxLatencyMillis,D.payload.minLatency=this.b.minLatencyMillis,D.payload.animatedLatency=this.b.animatedLatencyMillis,D.payload.ssrc=
m,D.payload.clockRate=q,D.payload.aesKey=a,D.payload.aesIvMask=b,f?(D.payload.channels=2,D.payload.maxBitrate=this.b.audioBitrate,D.payload.maxFrameRate=100):(D.payload.minBitrate=this.b.minVideoBitrate,D.payload.maxBitrate=this.b.maxVideoBitrate,D.payload.maxFrameRate=this.b.maxFrameRate),c.push(new $G(e,D));return c};
var XG=function(a,b,c){b&&!c.some(function(a){return a.Yc==b})&&(w(a.l,"Destroying RTP stream not selected by the receiver: id="+b),PG.rtpStream.destroy(b),b=null);return b},VG=function(a,b){return new Promise(function(c,d){for(var e=[],f=0;f<b.length;++f){var g=b[f].params,m={index:f,codecName:g.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:g.payload.payloadType,ssrc:g.payload.ssrc,targetDelay:g.payload.animatedLatency,aesKey:g.payload.aesKey,aesIvMask:g.payload.aesIvMask,timeBase:"1/"+
g.payload.clockRate,receiverRtcpEventLog:a.b.enableLogging,rtpExtensions:["adaptive_playout_delay"]};a.b.dscpEnabled&&(m.receiverRtcpDscp=46);127==g.payload.payloadType?Object.assign(m,{type:"audio_source",bitRate:0<g.payload.maxBitrate?1E3*g.payload.maxBitrate:60*g.payload.maxFrameRate+g.payload.clockRate*g.payload.channels,sampleRate:g.payload.clockRate,channels:g.payload.channels}):Object.assign(m,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*g.payload.maxFrameRate)+"/1000",
maxBitRate:1E3*g.payload.maxBitrate,resolutions:[{width:a.b.maxWidth,height:a.b.maxHeight}]});e.push(m)}var q=a.h instanceof SG||a.g instanceof SG?"remoting":"mirroring",y={type:"OFFER",sessionId:a.F,seqNum:Lj(a.J),offer:{castMode:q,receiverGetStatus:!0,supportedStreams:e}};x(a.l,function(){return"Sending OFFER message: "+JSON.stringify(y)});OG(a.B,y,"ANSWER",1E4,function(b,e){if(null==b)d(e);else if("ok"==b.result&&b.a){if(b.b!=y.seqNum)return w(a.l,"Ignoring ANSWER for OFFER with different seqNum: "+
JSON.stringify(b)),!1;((e=b.a.f)&&e!=q||!e&&"mirroring"!=q)&&a.l.error("Expected receiver to ANSWER with castMode="+q+", but got: "+e);z(a.l,function(){return"Received ANSWER: "+JSON.stringify(b)});c(b.a)}else d(Error("Non-OK ANSWER received: "+JSON.stringify(b)));return!0})})},WG=function(a,b,c){if(b.a.length!=b.b.length)return a.l.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(b)),[];for(var d=[],e={},f=0;f<b.a.length;e={candidate:e.candidate},++f){var g=b.a[f];if(0>g||g>=
c.length)return a.l.error("Receiver selected invalid index ("+g+" < "+c.length+") in ANSWER: "+JSON.stringify(b)),[];e.candidate=c[g];if(d.some(function(a){return function(b){return b.Yc==a.candidate.Yc}}(e)))return a.l.error("Receiver selected same RTP stream twice in ANSWER: "+JSON.stringify(b)),[];e.candidate.params.payload.feedbackSsrc=b.b[g];if(d.some(function(a){return function(b){return b.params.payload.feedbackSsrc==a.candidate.params.payload.feedbackSsrc}}(e)))return a.l.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+
JSON.stringify(b)),[];d.push(e.candidate)}return d},YG=function(a,b,c){var d=null,e=function(){d&&(PG.rtpStream.onStarted.removeListener(d),d=null)};return(new Promise(function(e,g){var f=b.g||2344;x(a.l,function(){return"Starting RTP streams to receiver at "+(a.j+":"+f)+(" for selected offers: "+JSON.stringify(c))});var q=a.v||-1;a.b.dscpEnabled&&(x(a.l,"Enabled DSCP in sender."),PG.udpTransport.setOptions(q,{DSCP:!0}));PG.udpTransport.setDestination(q,{address:a.j,port:f});var y=new Set(c.map(function(a){return a.Yc}));
d=function(a){y.delete(a);0==y.size&&e()};PG.rtpStream.onStarted.addListener(d);for(var q=ja(c),D=q.next();!D.done;D=q.next())D=D.value,PG.rtpStream.toggleLogging(D.Yc,a.b.enableLogging),PG.rtpStream.start(D.Yc,D.params);setTimeout(function(){g(Error("Timeout: RTP streams failed to start."))},1E4)})).then(e).catch(function(a){e();throw a;})},QG=function(a,b,c){var d=this;return a&&b in a?function(){try{a[b](c)}catch(e){d.l.error("Error from testHooks."+b,e)}}:function(){}},$G=function(a,b){this.Yc=
a;this.params=b},SG=function(){};var bH=function(a,b,c,d,e,f){b=Math.floor(16777216*Math.random()).toString(16);b="000000".substring(b.length)+b;var g=a.mediaSource.replace("urn:x-org.chromium.media:source:tab:","urn:x-org.chromium.media:source:tab_content_remoting:");b=Jj("undefined","cast",b,g,!0,a.description,a.iconUrl);b.forDisplay=!1;b.offTheRecord=a.offTheRecord;b.pb=a.pb;this.o=b;this.v=new RG(this.o.pb,c,d,e,f);this.j=e;this.f=new mG;this.b=new aH;this.l=v("mr.mirror.cast.MediaRemoter");this.a=this.g=this.h=this.m=null};
h=bH.prototype;h.start=function(a){var b=this;return oG(this.f,1,function(c){b.m=a;b.h=Po(b);sG(c,2);return Promise.resolve()})};h.stop=function(){var a=this;return qG(this.f,function(b){return cH(a).then(function(){var c=No(),d=a.Jb(),e=c.o.get(d.id);e&&(x(c.l,"Unregistering remoter with route: "+d.id),e.a=null,c.o.delete(d.id),c.b.Qc(c,d),Bo(c));a.h=null;a.m=null;sG(b,1)})})};h.Jb=function(){return this.o};
h.fl=function(a){var b=this;z(this.l,function(){return"Processing control message: "+a});var c=a.split(":"),d=(c.find(function(a){return a.startsWith("session=")})||"").substring(8);if(0==d.length)return this.l.error("Missing valid 'session' field in control message: "+a),Promise.resolve();switch(c[0]){case "START_CAST_REMOTING":return dH(this,d).catch(function(a){b.l.error("Failed to start remoting",a);eH(b,d)});case "START_CAST_REMOTING_STREAMS":var e=c.some(function(a){return"audio=Y"==a}),c=c.some(function(a){return"video=Y"==
a});return fH(this,d,e,c).then(this.w.bind(this)).catch(function(a){b.l.error("Failed to start remoting streams",a);eH(b,d)});case "STOP_CAST_REMOTING":return gH(this,d).catch(function(a){b.l.error("Failed to stop remoting",a);eH(b,d)}).then(function(){b.w("STOPPED_CAST_REMOTING:session="+d)});default:this.l.error("Unknown control message: "+a)}return Promise.resolve()};h.Ml=function(a){return hH(this.b,a)};
var dH=function(a,b){if(null!=a.a)return Promise.reject(Error("Attempt to start a second session ("+b+") during existing session ("+a.a+")."));a.a=b;var c=!1;x(a.l,function(){c=!0;return"Starting next media remoting session (id="+b+")."});c&&iH(a.b,function(b){return x(a.l,b)});jH(a.b);return oG(a.f,2,function(b){return(0,a.m)().then(function(c){a.g=c;MG(a.j,"RPC",function(b){if(b.rpc){var c=a.b;b=b.rpc;c.j&&(++c.m,c.b+=b.length,c.j(b))}});sG(b,3)}).catch(function(c){return cH(a).then(function(){sG(b);
throw c;})})})},fH=function(a,b,c,d){return a.a!=b?Promise.reject(Error("Cannot start streams for an unknown session ("+b+") during existing session ("+a.a+")")):oG(a.f,3,function(e){return a.v.start(c?new SG:null,d?new SG:null,function(c){a.l.error("Error during streaming: "+c);eH(a,b)}).then(function(c){var d="STARTED_CAST_REMOTING_STREAMS:session="+b;c.Bg&&(d+=":audio_stream_id="+c.Bg);c.ti&&(d+=":video_stream_id="+c.ti);kH(a.b,function(b){return a.j.sendMessage(b)},function(b){var c=a.h;c.a&&
c.a(b)});sG(e,4);return d}).catch(function(b){return cH(a).then(function(){sG(e);throw b;})})})},gH=function(a,b){if(a.a!=b)return Promise.reject(Error("Attempting to stop an unknown session ("+b+") during existing session ("+a.a+")."));a.a=null;return pG(a.f,function(b){return cH(a).then(function(){return(0,a.g)()}).then(function(){a.g=null;sG(b,2)})})},cH=function(a){return a.v.stop().then(function(){NG(a.j,"RPC");lH(a.b);mH(a.b)})};
bH.prototype.w=function(a){this.h?(z(this.l,function(){return"Sending control message to browser: "+a}),Qo(this.h,a)):z(this.l,function(){return"Dropping control message to browser: "+a})};
var eH=function(a,b){a.w("FAILED_CAST_REMOTING:session="+b)},No=function(){return up(wi.get("mr.ProviderManager")||null,"cast")},aH=function(){this.j=this.g=this.a=null;this.v=this.b=this.m=this.f=this.w=0;this.h=null},jH=function(a){a.a=[];nH(a,performance.now())},kH=function(a,b,c){a.g=b;a.j=c;a.a?(b=a.a,a.a=null,b.forEach(function(b){return hH(a,b.data).then(b.Ol,b.Zh)})):nH(a,performance.now())},lH=function(a){if(a.a){var b=Error("Stop before delivering pending message");a.a.forEach(function(a){return a.Zh(b)});
a.a=null}a.g=null;a.j=null},hH=function(a,b){if(a.g){var c=btoa(String.fromCharCode.apply(null,b));++a.w;a.f+=b.length;return a.g({type:"RPC",rpc:c})}return a.a?new Promise(function(c,e){a.a.push({data:b,Ol:c,Zh:e})}):Promise.reject(Error("RPC pipe not started"))},iH=function(a,b){mH(a);a.h=setInterval(function(){var c;if(a.a)c=a.a.length+" messages are waiting to send.";else{c=performance.now();var d=(c-a.v)/1E3,d="Over the past "+d.toFixed(1)+" seconds, sent "+(a.w+" messages ("+Math.round(a.f/
d)+" bytes/sec) and ")+("received "+a.m+" messages ("+Math.round(a.b/d)+" ")+"bytes/sec).";nH(a,c);c=d}b(c)},3E3)},mH=function(a){null!=a.h&&(clearInterval(a.h),a.h=null)},nH=function(a,b){a.w=0;a.f=0;a.m=0;a.b=0;a.v=b};var oH=function(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null},pH=function(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var qH=function(a,b,c,d,e){this.f=new RG(a,b,c,d,void 0===e?null:e);this.l=v("mr.mirror.cast.MediaStreamer");this.h=new mG;this.g=this.b=this.a=this.j=null};qH.prototype.start=function(a,b){var c=this;return oG(this.h,1,function(d){c.j=a;c.a=oH(a);c.a&&"ended"==c.a.readyState&&(c.a=null);c.b=pH(a);c.b&&"ended"==c.b.readyState&&(c.b=null);if(!c.a&&!c.b)return sG(d),Promise.reject(Error("No MediaStream tracks to stream."));c.g=b;return c.f.start(c.a,c.b,b).then(function(){return sG(d,2)})})};
qH.prototype.stop=function(){var a=this;return qG(this.h,function(b){return a.f.stop().then(function(){a.a=null;a.b=null;a.j=null;a.g=null;sG(b,1)})})};var rH=function(a){return oG(a.h,2,function(b){x(a.l,"Suspending media streaming...");return a.f.stop().then(function(){x(a.l,"Suspended media streaming.");sG(b,3)})})};
qH.prototype.resume=function(){var a=this;return oG(this.h,3,function(b){a.a&&"ended"==a.a.readyState&&(a.a=null);a.b&&"ended"==a.b.readyState&&(a.b=null);if(!a.a&&!a.b)return Promise.reject(Error("Cannot resume: All tracks have ended."));x(a.l,"Resuming media streaming...");return a.f.start(a.a,a.b,a.g).then(function(){x(a.l,"Resumed media streaming.");sG(b,2)})})};qH.prototype.getStats=function(a){return this.f.getStats(a)};var sH=function(a,b,c){this.g=a;this.h=b;this.f=c;this.l=v("mr.mirror.cast.WifiStatusMonitor");this.b=null;this.a=[]};sH.prototype.start=function(){var a=this;null==this.b&&(z(this.l,"Starting Wifi Status Monitoring."),this.a=[],MG(this.f,"STATUS_RESPONSE",function(b){return tH(a,b)}),this.b=setInterval(function(){return uH(a)},12E4),uH(this))};sH.prototype.stop=function(){null!=this.b&&(z(this.l,"Stopping Wifi Status Monitoring."),clearInterval(this.b),this.b=null,NG(this.f,"STATUS_RESPONSE"))};
var tH=function(a,b){if(null!=a.b)if(b.status){var c={};null!=b.status.a&&(c.wifiSnr=b.status.a);null!=b.status.b&&(c.wifiSpeed=b.status.b[3]);0==Object.keys(c).length?w(a.l,function(){return"No status fields populated in response: "+JSON.stringify(b)}):(c.timestamp=Date.now(),30==a.a.length&&a.a.shift(),a.a.push(c),x(a.l,function(){return"Current Wifi status: "+JSON.stringify(c)}))}else w(a.l,function(){return"Ignoring response without status: "+JSON.stringify(b)})},uH=function(a){a.f.sendMessage({type:"GET_STATUS",
sessionId:a.g,seqNum:Lj(a.h),get_status:["wifiSnr","wifiSpeed"]})};var vH=function(a,b,c){c=void 0===c?null:c;Ri.call(this,b);var d=b.pb;this.m=d.sessionId;this.F=d.Pf;this.B=a;this.H=c;this.l=v("mr.mirror.cast.Session");this.j=new mG;this.g=new Kj("mirror.cast.SeqNumGenerator");this.h=new LG(b.id);this.a=new qH(d,this.B,this.g,this.h,this.H);this.f=null;this.v=new sH(this.m,this.g,this.h);this.u=!1;this.w=null};ka(vH,Ri);
vH.prototype.start=function(a){var b=this;return oG(this.j,1,function(c){var d=new Rh("MediaRouter.CastStreaming.Session.Launch");return wH(b).then(function(c){b.u=c;return b.a.start(a,b.J.bind(b))}).then(function(){b.a.f.u&&(b.v.start(),xH(b));d.a();b.w=new Xh("MediaRouter.CastStreaming.Session.Length");sG(c,2);return b})})};
vH.prototype.stop=function(){var a=this;return qG(this.j,function(b){a.w&&(a.w.a(),a.w=null);a.v.stop();return a.a.stop().then(function(){return a.f?a.f.stop():Promise.resolve()}).then(function(){a.f=null;return a.u?yH(a):Promise.resolve()}).then(function(){a.u=!1;sG(b,4)})})};
vH.prototype.Yh=function(){var a={sessionId:this.m,seqNum:Lj(this.g),type:"PRESENTATION",icons:[]};this.A&&(a.title=this.A);this.iconUrl&&!this.o&&a.icons.push({url:this.iconUrl});x(this.l,"Sending session metadata update to receiver: "+this.m);this.h.sendMessage(a)};var zH=function(a){return ZG(a.a.f,a.v.a)};vH.prototype.getStats=function(){return this.a.getStats(this.v.a)};vH.prototype.J=function(a,b){this.l.error(a,b);this.stop()};
var wH=function(a){return a.B.useTdls?lG(a.F,!0).then(function(b){if("Connected"==b)return x(a.l,"Successfully enabled TDLS."),!0;w(a.l,"Did not enable TDLS: result="+b);return!1}).catch(function(b){w(a.l,"Error while calling enableTDLS()",b);return!1}):Promise.resolve(!1)},yH=function(a){return lG(a.F,!1).catch(function(b){return a.l.error("Error while turning TDLS back off",b)})},xH=function(a){AH(a).then(function(b){(b.a||[]).includes("video")?BH(a):w(a.l,function(){return"Receiver incapable of Media Remoting: "+
JSON.stringify(b)})}).catch(function(b){w(a.l,"None/Invalid capabilites response. Media Remoting disabled.",b)})},AH=function(a){return new Promise(function(b,c){var d={type:"GET_CAPABILITIES",sessionId:a.m,seqNum:Lj(a.g)};x(a.l,function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(d)});OG(a.h,d,"CAPABILITIES_RESPONSE",3E4,function(e,f){if(null==e)return c(f),!0;if("ok"!=e.result||!e.capabilities)return c(Error("Bad response: "+JSON.stringify(e))),!0;if(e.b!=d.seqNum)return x(a.l,function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+
JSON.stringify(e)}),!1;z(a.l,function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(e)});b(e.capabilities);return!0})})},BH=function(a){oG(a.j,2,function(b){a.f=new bH(a.b,0,a.B,a.g,a.h,a.H);return a.f.start(a.ia.bind(a)).catch(function(b){a.l.error("Media Remoting start failed: "+b.message,b)}).then(function(){return sG(b)})})};
vH.prototype.ia=function(){var a=this;return oG(this.j,2,function(b){return new Promise(function(c,d){rH(a.a).then(function(){sG(b,3);c(a.K.bind(a))}).catch(function(b){a.J("Failed to suspend MediaStreamer before starting remoting",b);d(b)})})})};vH.prototype.K=function(){var a=this;return oG(this.j,3,function(b){return new Promise(function(c,d){a.a.resume().then(function(){sG(b,2);c()}).catch(function(b){a.J("Failed resume MediaStreamer after ending remoting mode",b);d(b)})})})};var CH=function(){Gi.call(this,"cast_streaming")};ka(CH,Gi);h=CH.prototype;h.getName=function(){return"cast_streaming"};h.ae=function(a,b){return new vH(a,b,null)};h.Ee=function(){YF(0)};h.Ae=function(){YF(1)};h.Gf=function(){YF(2)};h.Be=function(){$h("MediaRouter.CastStreaming.Session.End")};h.Ce=function(a){ai("MediaRouter.CastStreaming.Start.Failure",a,ci)};h.De=function(){$h("MediaRouter.CastStreaming.Stream.End")};
h.Te=function(a){var b=this,c=zH(a).then(function(a){return a},function(a){w(b.G,"Get cast streaming logs failed.",a)});a=a.getStats().then(function(a){return a},function(a){w(b.G,"Get cast streaming stats failed.",a)});var d=new Promise(function(a){chrome.metricsPrivate.getIsCrashReportingEnabled(a)});return Promise.all([c,a,d]).then(function(a){var c=ja(a);a=c.next().value;var d=c.next().value,c=c.next().value;if(a){var e=new FileReader;e.onloadend=function(){yj("mr.temp.mirror.cast.Service.mirrorLogs",
e.result)};e.readAsBinaryString(a)}c&&(a&&eG()?aG(a,void 0,b.Ek.bind(b)):d&&$F("stats.json",new Blob([JSON.stringify(d)],{type:"application/json"}),void 0,void 0))})};h.Ek=function(a){a&&(dG().a=Date.now())};h.nf=function(a){var b=this;x(this.G,"Received message to upload logs for "+a);return this.a?zH(this.a).then(function(b){return aG(b,a)},function(c){w(b.G,"Get cast streaming logs failed.",c);return DH(b,a)}):Promise.resolve(DH(this,a))};
var DH=function(a,b){var c=window.localStorage["mr.temp.mirror.cast.Service.mirrorLogs"];if(c){window.localStorage.removeItem("mr.temp.mirror.cast.Service.mirrorLogs");x(a.G,"Uploading saved logs for feedback.");a=new Uint8Array(c.length);for(var d=0;d<a.length;d++)a[d]=c.charCodeAt(d);return aG(new Blob([a],{type:"application/gzip"}),b)}},EH=new CH;Ei("mr.mirror.cast.Service",EH);
